# Generated by Django 3.2.25 on 2024-07-18 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCate', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Dificultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivelDificultad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Puntuaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.IntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.categoria')),
                ('dificultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.dificultad')),
            ],
        ),
        migrations.CreateModel(
            name='PalabrasAhorcado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabras', models.CharField(max_length=100)),
                ('pistas', models.CharField(max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.categoria')),
                ('dificultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.dificultad')),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intentos_restantes', models.IntegerField(default=6)),
                ('estado', models.CharField(choices=[('en_progreso', 'En Progreso'), ('ganado', 'Ganado'), ('perdido', 'Perdido')], default='en_progreso', max_length=11)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('palabra_oculta', models.CharField(max_length=100)),
                ('palabras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.palabrasahorcado')),
            ],
        ),
        migrations.CreateModel(
            name='Intentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letra', models.CharField(max_length=1)),
                ('es_correcto', models.BooleanField()),
                ('fecha_intento', models.DateTimeField(auto_now_add=True)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.juego')),
            ],
        ),
    ]
