# Generated by Django 5.0.7 on 2024-07-27 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameUsuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField()),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('palabra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.palabrasahorcado')),
            ],
        ),
    ]
