# Generated by Django 5.0.7 on 2024-07-27 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gameusuarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameusuarios',
            old_name='puntuacion',
            new_name='puntaje',
        ),
        migrations.AddField(
            model_name='gameusuarios',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.categoria'),
        ),
        migrations.AddField(
            model_name='gameusuarios',
            name='dificultad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.dificultad'),
        ),
    ]
