# Generated by Django 5.0.7 on 2024-07-27 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_rename_puntuacion_gameusuarios_puntaje_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameUsuarios',
        ),
    ]
